"""test migration

Revision ID: d7bef0e0c44a
Revises: 
Create Date: 2026-03-14 02:29:24.697773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7bef0e0c44a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_dashboard_cache_cache_key'), table_name='dashboard_cache')
    op.drop_column('dashboard_cache', 'cache_key')
    op.drop_index(op.f('idx_deal_events_created'), table_name='deal_events')
    op.drop_index(op.f('ix_deal_events_dedupe_key'), table_name='deal_events')
    op.drop_index(op.f('uq_deal_events_dedupe_key'), table_name='deal_events')
    op.drop_index(op.f('ix_game_interest_signals_click_count_desc'), table_name='game_interest_signals')
    op.drop_index(op.f('ix_game_interest_signals_wishlist_watchlist_desc'), table_name='game_interest_signals')
    op.drop_index(op.f('uq_game_price_lows_game_id'), table_name='game_price_lows')
    op.drop_index(op.f('idx_game_prices_game_id'), table_name='game_prices')
    op.drop_index(op.f('idx_game_prices_recorded'), table_name='game_prices')
    op.drop_index(op.f('ix_game_prices_game_id_recorded_at_desc'), table_name='game_prices')
    op.drop_index(op.f('ix_game_prices_game_id_recorded_id_desc'), table_name='game_prices')
    op.alter_column('game_snapshots', 'buy_recommendation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'buy_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'predicted_sale_confidence',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'predicted_sale_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_snapshots_buy_score'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_discount'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_momentum'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_players'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_price'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_trending'), table_name='game_snapshots')
    op.drop_index(op.f('idx_snapshots_worth_buying'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_avg_player_count_desc'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_deal_score_desc'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_latest_discount_percent_desc'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_released_discovery'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_review_score_review_count_desc'), table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_upcoming_hot'), table_name='game_snapshots')
    op.drop_index(op.f('uq_game_snapshots_game_id'), table_name='game_snapshots')
    op.drop_index(op.f('ix_games_developer_trgm'), table_name='games', postgresql_ops={'developer': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_games_is_released_name'), table_name='games')
    op.drop_index(op.f('ix_games_name_trgm'), table_name='games', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_games_publisher_trgm'), table_name='games', postgresql_ops={'publisher': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_job_status_updated_at'), table_name='job_status')
    op.drop_index(op.f('uq_latest_game_prices_game_id'), table_name='latest_game_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_latest_game_prices_game_id'), 'latest_game_prices', ['game_id'], unique=True)
    op.create_index(op.f('ix_job_status_updated_at'), 'job_status', ['updated_at'], unique=False)
    op.create_index(op.f('ix_games_publisher_trgm'), 'games', ['publisher'], unique=False, postgresql_ops={'publisher': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_games_name_trgm'), 'games', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_games_is_released_name'), 'games', ['is_released', 'name'], unique=False)
    op.create_index(op.f('ix_games_developer_trgm'), 'games', ['developer'], unique=False, postgresql_ops={'developer': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('uq_game_snapshots_game_id'), 'game_snapshots', ['game_id'], unique=True)
    op.create_index(op.f('ix_game_snapshots_upcoming_hot'), 'game_snapshots', ['is_upcoming', sa.literal_column('upcoming_hot_score DESC'), 'release_date'], unique=False)
    op.create_index(op.f('ix_game_snapshots_review_score_review_count_desc'), 'game_snapshots', [sa.literal_column('review_score DESC'), sa.literal_column('review_count DESC')], unique=False)
    op.create_index(op.f('ix_game_snapshots_released_discovery'), 'game_snapshots', ['is_upcoming', 'is_released', sa.literal_column('deal_score DESC')], unique=False)
    op.create_index(op.f('ix_game_snapshots_latest_discount_percent_desc'), 'game_snapshots', [sa.literal_column('latest_discount_percent DESC')], unique=False)
    op.create_index(op.f('ix_game_snapshots_deal_score_desc'), 'game_snapshots', [sa.literal_column('deal_score DESC')], unique=False)
    op.create_index(op.f('ix_game_snapshots_avg_player_count_desc'), 'game_snapshots', [sa.literal_column('avg_player_count DESC')], unique=False)
    op.create_index(op.f('idx_snapshots_worth_buying'), 'game_snapshots', ['worth_buying_score'], unique=False)
    op.create_index(op.f('idx_snapshots_trending'), 'game_snapshots', ['trending_score'], unique=False)
    op.create_index(op.f('idx_snapshots_price'), 'game_snapshots', ['latest_price'], unique=False)
    op.create_index(op.f('idx_snapshots_players'), 'game_snapshots', ['current_players'], unique=False)
    op.create_index(op.f('idx_snapshots_momentum'), 'game_snapshots', ['momentum_score'], unique=False)
    op.create_index(op.f('idx_snapshots_discount'), 'game_snapshots', ['latest_discount_percent'], unique=False)
    op.create_index(op.f('idx_snapshots_buy_score'), 'game_snapshots', ['buy_score'], unique=False)
    op.alter_column('game_snapshots', 'predicted_sale_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'predicted_sale_confidence',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'buy_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('game_snapshots', 'buy_recommendation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_game_prices_game_id_recorded_id_desc'), 'game_prices', ['game_id', sa.literal_column('recorded_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index(op.f('ix_game_prices_game_id_recorded_at_desc'), 'game_prices', ['game_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_game_prices_recorded'), 'game_prices', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_game_prices_game_id'), 'game_prices', ['game_id'], unique=False)
    op.create_index(op.f('uq_game_price_lows_game_id'), 'game_price_lows', ['game_id'], unique=True)
    op.create_index(op.f('ix_game_interest_signals_wishlist_watchlist_desc'), 'game_interest_signals', [sa.literal_column('wishlist_count DESC'), sa.literal_column('watchlist_count DESC')], unique=False)
    op.create_index(op.f('ix_game_interest_signals_click_count_desc'), 'game_interest_signals', [sa.literal_column('click_count DESC')], unique=False)
    op.create_index(op.f('uq_deal_events_dedupe_key'), 'deal_events', ['event_dedupe_key'], unique=True)
    op.create_index(op.f('ix_deal_events_dedupe_key'), 'deal_events', ['event_dedupe_key'], unique=False)
    op.create_index(op.f('idx_deal_events_created'), 'deal_events', [sa.literal_column('created_at DESC')], unique=False)
    op.add_column('dashboard_cache', sa.Column('cache_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_dashboard_cache_cache_key'), 'dashboard_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###
